## 06 ``numpy.array`` 合并和分割

In [1]:
import numpy as np

### ``numpy.array`` 的合并

In [2]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [7]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [8]:
z = np.array([666, 666, 666])
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

In [12]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [15]:
np.concatenate([A, A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [16]:
np.concatenate([A, z])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [18]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [19]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [20]:
B = np.full((2,2), 100)

In [21]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

In [22]:
np.hstack([A, z])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

### ``numpy.array`` 的分割

In [23]:
x = np.arange(10)
x    

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x1, x2, x3 = np.split(x, [3, 7])

In [25]:
x1

array([0, 1, 2])

In [26]:
x2

array([3, 4, 5, 6])

In [27]:
x3

array([7, 8, 9])

In [28]:
x1, x2 = np.split(x, [5])

In [29]:
x1

array([0, 1, 2, 3, 4])

In [30]:
x2

array([5, 6, 7, 8, 9])

In [31]:
A = np.arange(16).reshape((4, 4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
A1, A2 = np.split(A, [2])

In [33]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
A1, A2 = np.split(A, [2], axis=1)

In [36]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [37]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [38]:
upper, lower = np.vsplit(A, [2])

In [39]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [40]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
left, right = np.hsplit(A, [2])

In [42]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [43]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [44]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
X, y = np.hsplit(data, [-1])

In [46]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [47]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [48]:
y[:, 0]

array([ 3,  7, 11, 15])