## 09 ``Numpy`` 中arg运算

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, 1000000)

### 索引

In [10]:
a = np.argmin(x)

In [11]:
x[a]

-4.630678604233429

In [12]:
np.min(x)

-4.630678604233429

In [13]:
b = np.argmax(x)

In [14]:
x[b]

4.46409911068091

In [15]:
np.max(x)

4.46409911068091

### 排序和使用索引

In [24]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
np.random.shuffle(x)
x

array([15,  7,  8,  9,  0, 12, 13, 11,  5,  1,  3, 14,  6,  2,  4, 10])

In [28]:
x

array([15,  7,  8,  9,  0, 12, 13, 11,  5,  1,  3, 14,  6,  2,  4, 10])

In [29]:
x.sort()

In [30]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
X = np.random.randint(10, size=(4,4))
X

array([[4, 8, 1, 1],
       [0, 1, 2, 6],
       [9, 4, 4, 0],
       [3, 8, 2, 0]])

In [33]:
np.sort(X, axis=0)

array([[0, 1, 1, 0],
       [3, 4, 2, 0],
       [4, 8, 2, 1],
       [9, 8, 4, 6]])

In [34]:
np.sort(X, axis=1)

array([[1, 1, 4, 8],
       [0, 1, 2, 6],
       [0, 4, 4, 9],
       [0, 2, 3, 8]])

#### 使用索引

In [35]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
np.random.shuffle(x)
x

array([ 5, 10, 12,  8,  4,  3,  2,  6,  7, 15, 13, 11,  0,  9,  1, 14])

In [42]:
np.argsort(x)

array([12, 14,  6,  5,  4,  0,  7,  8,  3, 13,  1, 11,  2, 10, 15,  9])

In [43]:
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  5,  6, 10,  7, 15, 13, 11,  8,  9, 12, 14])

In [44]:
np.argpartition(x, 3)

array([12, 14,  6,  5,  4,  0,  7,  1,  8,  9, 10, 11,  3, 13,  2, 15])

In [45]:
X

array([[4, 8, 1, 1],
       [0, 1, 2, 6],
       [9, 4, 4, 0],
       [3, 8, 2, 0]])

In [46]:
np.argsort(X, axis=1)

array([[2, 3, 0, 1],
       [0, 1, 2, 3],
       [3, 1, 2, 0],
       [3, 2, 0, 1]])

In [47]:
np.argpartition(X, 2, axis=1)

array([[2, 3, 0, 1],
       [0, 1, 2, 3],
       [3, 1, 2, 0],
       [3, 2, 0, 1]])