## 05 ``numpy.array`` 基本操作

In [3]:
import numpy as np
np.random.seed(0)

x = np.arange(10)

In [56]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
X = np.arange(15).reshape((3, 5))


In [62]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### ``numpy.array`` 的基本属性

In [63]:
x.ndim

1

In [64]:
X.ndim

2

In [65]:
x.shape

(10,)

In [66]:
X.shape

(3, 5)

In [67]:
x.size

10

In [68]:
X.size

15

### ``numpy.array`` 的数据访问

In [69]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x[0]

0

In [71]:
x[-1]

9

In [72]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [73]:
X[0][0] # 不建议！

0

In [74]:
X[0, 0]

0

In [75]:
X[0, -1]

4

In [76]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x[0:5]

array([0, 1, 2, 3, 4])

In [78]:
x[:5]

array([0, 1, 2, 3, 4])

In [79]:
x[5:]

array([5, 6, 7, 8, 9])

In [80]:
x[4:7]

array([4, 5, 6])

In [81]:
x[::2]

array([0, 2, 4, 6, 8])

In [82]:
x[1::2]

array([1, 3, 5, 7, 9])

In [83]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [84]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [85]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [30]:
X[:2][:3] # 结果不一样，在numpy中使用","做多维索引

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [87]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [88]:
X[0, :]

array([0, 1, 2, 3, 4])

In [89]:
X[:, 0]

array([ 0,  5, 10])

### Subarray of ``numpy.array``

In [90]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [91]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [92]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [93]:
X[0, 0] = 0
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [94]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [95]:
subX = X[:2, :3].copy()

In [96]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [97]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Reshape

In [98]:
x.shape

(10,)

In [99]:
x.ndim

1

In [100]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [101]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
A = x.reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [103]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
B = x.reshape(1, 10)
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [105]:
B.ndim

2

In [106]:
B.shape

(1, 10)

In [107]:
x.reshape(-1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [108]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [109]:
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [110]:
x.reshape(3, -1)

ValueError: cannot reshape array of size 10 into shape (3,newaxis)