## 08 ``Numpy`` 中的聚合操作

### sum

In [2]:
import numpy as np

L = np.random.random(100)
sum(L)

50.81764949656418

In [5]:
np.sum(L)

50.81764949656418

In [6]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

72.6 ms ± 3.46 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
189 µs ± 270 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


### min, max

In [7]:
np.min(big_array)

5.497110660002136e-07

In [8]:
np.max(big_array)

0.9999986247430365

In [9]:
big_array.min()

5.497110660002136e-07

In [10]:
big_array.max()

0.9999986247430365

In [11]:
big_array.sum()

499975.459295088

### 多维度聚合

In [12]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
np.sum(X)

120

In [14]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [15]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

注意：axis描述的是将要被压缩的维度。

### 其他聚合操作

In [16]:
np.prod(X)

0

In [20]:
np.prod(X + 1)

20922789888000

In [21]:
np.mean(X)

7.5

In [22]:
np.median(X)

7.5

In [23]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [24]:
np.median(v)

2.0

In [26]:
np.percentile(big_array, q=50)

0.49977685306305486

In [27]:
np.median(big_array)

0.49977685306305486

In [28]:
np.percentile(big_array, q=100)

0.9999986247430365

In [29]:
np.max(big_array)

0.9999986247430365

In [30]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

5.497110660002136e-07
0.25011223218426504
0.49977685306305486
0.7499800009068559
0.9999986247430365


In [31]:
np.var(big_array)

0.08334085665065333

In [32]:
np.std(big_array)

0.28868816506856204

In [41]:
x = np.random.normal(0, 1, 1000000)

In [42]:
np.mean(x)

0.0016473376280933144

In [43]:
np.std(x)

1.0007188935583173